import type { ErrorPattern } from '../types.js';

export const COMMON_ERROR_PATTERNS: ErrorPattern[] = [
  {
    id: 'metro-bundler',
    platform: 'common',
    severity: 'critical',
    title: 'Metro Bundler Resolution Error',
    cause:
      'Metro cannot resolve a module, either because it does not exist or node_modules is corrupt.',
    patterns: [
      /Unable to resolve module/i,
      /Metro Bundler.*cannot find module/i,
      /error: bundling failed/i,
      /ENOENT.*node_modules/i,
    ],
    fixes: [
      'Run: npx react-native start --reset-cache',
      'Delete node_modules and reinstall: rm -rf node_modules && npm install',
      'Verify the import path is correct (case-sensitive on macOS)',
    ],
    autoFixable: true,
    fixId: 'metro-cache-reset',
  },
  {
    id: 'metro-cache',
    platform: 'common',
    severity: 'warning',
    title: 'Metro Cache Corruption',
    cause:
      'The Metro bundler cache is stale or corrupted, often after package updates.',
    patterns: [
      /EMFILE.*too many open files/i,
      /Haste module map/i,
      /Metro.*cache/i,
      /Watchman.*crawl/i,
    ],
    fixes: [
      'Reset Metro cache: npx react-native start --reset-cache',
      'Clear watchman: watchman watch-del-all',
      'Delete Metro cache: rm -rf /tmp/metro-*',
    ],
    autoFixable: true,
    fixId: 'metro-cache-reset',
  },
  {
    id: 'node-modules',
    platform: 'common',
    severity: 'warning',
    title: 'node_modules Corruption / Mismatch',
    cause:
      'node_modules is out of sync with package.json, often after a git pull or changing package managers.',
    patterns: [
      /Cannot find module '.*' from '.*node_modules/i,
      /Error: Cannot find module/i,
      /Module not found.*node_modules/i,
    ],
    fixes: [
      'Delete node_modules: rm -rf node_modules',
      'Reinstall: npm install (or yarn / pnpm install)',
      'If lock file is outdated: delete package-lock.json and reinstall',
    ],
    autoFixable: true,
    fixId: 'node-modules-reinstall',
  },
  {
    id: 'rn-version-mismatch',
    platform: 'common',
    severity: 'warning',
    title: 'React Native Version Mismatch',
    cause:
      'The react-native package version does not match the native code in the project.',
    patterns: [
      /React Native version mismatch/i,
      /React Native.*expects to be running.*but.*is/i,
      /YellowBox.*version.*incompatible/i,
    ],
    fixes: [
      'Ensure package.json dependencies match the native project',
      'Run the RN upgrade tool: npx react-native upgrade',
      'Manually align iOS Podfile / android build.gradle with the package.json version',
    ],
    autoFixable: false,
  },
  {
    id: 'hermes-syntax-error',
    platform: 'common',
    severity: 'critical',
    title: 'Hermes JavaScript Syntax Error',
    cause: 'Hermes does not support all JavaScript features or there is a syntax error in the bundle.',
    patterns: [
      /SyntaxError.*Hermes/i,
      /CompileJS.*failed/i,
      /Error: Unexpected token/i,
      /Hermes.*internal bytecode.*version mismatch/i,
    ],
    fixes: [
      'Check for unsupported JS features (e.g., with statement)',
      'Clear Metro cache: npx react-native start --reset-cache',
      'Verify babel.config.js includes correct presets',
      'Rebuild: rm -rf android/app/build ios/build',
    ],
    autoFixable: false,
  },
  {
    id: 'native-module-not-found',
    platform: 'common',
    severity: 'critical',
    title: 'Native Module Not Found / Not Linked',
    cause: 'A React Native library with native code is not properly linked or the native build is stale.',
    patterns: [
      /Invariant Violation.*Native module .* cannot be null/i,
      /NativeModules\..*is null/i,
      /requireNativeComponent.*was not found/i,
      /TurboModuleRegistry.*could not find/i,
    ],
    fixes: [
      'Run: npx react-native link <package> (legacy linking)',
      'iOS: cd ios && pod install',
      'Android: cd android && ./gradlew clean',
      'Rebuild the app (native changes require a full rebuild)',
    ],
    autoFixable: false,
  },
  {
    id: 'invariant-violation',
    platform: 'common',
    severity: 'critical',
    title: 'Invariant Violation (React Runtime Error)',
    cause: 'A React/RN runtime check failed. Common causes: rendering null, invalid component, or missing context provider.',
    patterns: [
      /Invariant Violation/i,
      /Element type is invalid.*expected a string.*but got: undefined/i,
      /Text strings must be rendered within a <Text> component/i,
    ],
    fixes: [
      'Check import statements for the failing component',
      'Ensure all text is wrapped in <Text> components',
      'Verify component default/named exports match imports',
      'Check that context providers wrap consuming components',
    ],
    autoFixable: false,
  },
  {
    id: 'out-of-memory-js',
    platform: 'common',
    severity: 'critical',
    title: 'JavaScript Out of Memory',
    cause: 'The JavaScript heap has run out of memory, often caused by memory leaks or processing large data.',
    patterns: [
      /JavaScript heap out of memory/i,
      /FATAL ERROR.*Reached heap limit/i,
      /Allocation failed.*JavaScript heap/i,
    ],
    fixes: [
      'Increase Node.js memory: NODE_OPTIONS="--max-old-space-size=8192" npx react-native start',
      'Check for memory leaks: missing cleanup in useEffect, large state objects',
      'Use FlatList/FlashList instead of ScrollView for large lists',
      'Profile with React DevTools to find components holding large data',
    ],
    autoFixable: false,
  },
  {
    id: 'expo-config-plugin-error',
    platform: 'common',
    severity: 'warning',
    title: 'Expo Config Plugin Error',
    cause: 'An Expo config plugin failed during prebuild or build.',
    patterns: [
      /Config plugin.*threw an error/i,
      /Cannot apply.*plugin.*to the project/i,
      /expo-module.*not found/i,
    ],
    fixes: [
      'Run: npx expo prebuild --clean',
      'Check app.json plugins array for correct configuration',
      'Verify the library version is compatible with your Expo SDK version',
      'Remove node_modules and reinstall: rm -rf node_modules && npm install',
    ],
    autoFixable: false,
  },
  {
    id: 'auto-linking-fail',
    platform: 'common',
    severity: 'warning',
    title: 'React Native Auto-linking Failed',
    cause: 'A native library was not detected by the auto-linking system.',
    patterns: [
      /auto-?linking.*could not.*find/i,
      /react-native\.config\.js.*not found/i,
      /RNAutolinked.*missing/i,
    ],
    fixes: [
      'Run: npx react-native config (verify the library appears)',
      'Check that the library has react-native.config.js or is listed in package.json dependencies',
      'iOS: cd ios && pod install',
      'Android: cd android && ./gradlew clean',
    ],
    autoFixable: false,
  },
];
