import type { EnvSetupGuide } from '../types.js';

export const RN_ENV_SETUP_GUIDES: EnvSetupGuide[] = [
  {
    id: 'macos-ios-setup',
    name: 'macOS — iOS Development Setup',
    description: 'Complete setup guide for React Native iOS development on macOS.',
    keywords: ['macos', 'mac', 'ios', 'xcode', 'cocoapods', 'simulator', 'apple', 'setup mac'],
    os: 'macos',
    targetPlatform: 'ios',
    prerequisites: ['macOS 13+ (Ventura or later)', '16GB+ RAM recommended', '50GB+ free disk space'],
    steps: [
      {
        order: 1,
        title: 'Install Xcode',
        description: 'Download from Mac App Store or Apple Developer site. Install Command Line Tools.',
        commands: ['xcode-select --install'],
        tips: ['Xcode 15+ required for RN 0.75+', 'Accept license: sudo xcodebuild -license accept'],
      },
      {
        order: 2,
        title: 'Install Homebrew',
        description: 'macOS package manager for installing development tools.',
        commands: ['/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'],
      },
      {
        order: 3,
        title: 'Install Node.js',
        description: 'Install Node.js 18+ via nvm or Homebrew.',
        commands: ['brew install nvm', 'nvm install 20', 'nvm use 20'],
        tips: ['nvm is recommended over system Node for easy version switching'],
      },
      {
        order: 4,
        title: 'Install Watchman',
        description: 'File watcher for Metro bundler. Significantly improves performance.',
        commands: ['brew install watchman'],
      },
      {
        order: 5,
        title: 'Install CocoaPods',
        description: 'iOS dependency manager required for React Native.',
        commands: ['sudo gem install cocoapods'],
        tips: ['If Ruby gem issues: brew install cocoapods instead'],
      },
      {
        order: 6,
        title: 'Install iOS Simulator',
        description: 'Open Xcode → Settings → Platforms → Download iOS Simulator runtime.',
        tips: ['Download only the simulators you need to save disk space'],
      },
      {
        order: 7,
        title: 'Verify setup',
        description: 'Create a test project and build it.',
        commands: ['npx @react-native-community/cli@latest init TestApp', 'cd TestApp && npx react-native run-ios'],
      },
    ],
  },
  {
    id: 'macos-android-setup',
    name: 'macOS — Android Development Setup',
    description: 'Complete setup guide for React Native Android development on macOS.',
    keywords: ['macos', 'mac', 'android', 'android studio', 'emulator', 'jdk', 'java', 'setup android mac'],
    os: 'macos',
    targetPlatform: 'android',
    prerequisites: ['macOS 12+', '16GB+ RAM (emulator is memory-intensive)', '30GB+ free disk space'],
    steps: [
      {
        order: 1,
        title: 'Install Java 17 (JDK)',
        description: 'React Native 0.73+ requires Java 17.',
        commands: ['brew install openjdk@17'],
        tips: [
          'Add to ~/.zshrc: export JAVA_HOME=$(/usr/libexec/java_home -v 17)',
          'Verify: java -version should show 17.x',
        ],
      },
      {
        order: 2,
        title: 'Install Android Studio',
        description: 'Download from developer.android.com. Includes SDK Manager and Emulator.',
        commands: ['brew install --cask android-studio'],
      },
      {
        order: 3,
        title: 'Configure Android SDK',
        description: 'Open Android Studio → SDK Manager → install required components.',
        tips: [
          'SDK Platforms: Android 14 (API 34)',
          'SDK Tools: Android SDK Build-Tools 34, Android Emulator, Android SDK Platform-Tools',
          'NDK (if needed for native modules)',
        ],
      },
      {
        order: 4,
        title: 'Set environment variables',
        description: 'Add Android SDK paths to your shell profile.',
        commands: [
          'echo \'export ANDROID_HOME=$HOME/Library/Android/sdk\' >> ~/.zshrc',
          'echo \'export PATH=$PATH:$ANDROID_HOME/emulator:$ANDROID_HOME/platform-tools\' >> ~/.zshrc',
          'source ~/.zshrc',
        ],
      },
      {
        order: 5,
        title: 'Create Android emulator',
        description: 'Use AVD Manager in Android Studio to create a virtual device.',
        tips: [
          'Recommended: Pixel 7 with API 34 system image',
          'Use x86_64 image on Intel Macs, arm64 on Apple Silicon',
          'Enable hardware acceleration for better performance',
        ],
      },
      {
        order: 6,
        title: 'Verify setup',
        description: 'Build and run on emulator.',
        commands: ['npx react-native run-android'],
        tips: ['Ensure emulator is running before building'],
      },
    ],
  },
  {
    id: 'windows-android-setup',
    name: 'Windows — Android Development Setup',
    description: 'Complete setup guide for React Native Android development on Windows.',
    keywords: ['windows', 'android', 'android studio', 'emulator', 'jdk', 'setup windows', 'powershell'],
    os: 'windows',
    targetPlatform: 'android',
    prerequisites: ['Windows 10/11 64-bit', '16GB+ RAM', 'BIOS virtualization enabled (for emulator)'],
    steps: [
      {
        order: 1,
        title: 'Install Chocolatey (package manager)',
        description: 'Windows package manager for installing dev tools.',
        commands: ['Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString(\'https://community.chocolatey.org/install.ps1\'))'],
      },
      {
        order: 2,
        title: 'Install Node.js and JDK 17',
        description: 'Install via Chocolatey for easy management.',
        commands: ['choco install -y nodejs-lts microsoft-openjdk17'],
      },
      {
        order: 3,
        title: 'Install Android Studio',
        description: 'Download from developer.android.com or install via Chocolatey.',
        commands: ['choco install -y androidstudio'],
      },
      {
        order: 4,
        title: 'Configure Android SDK',
        description: 'Same as macOS — install SDK Platform 34, Build Tools, Emulator.',
        tips: ['Default SDK location: %LOCALAPPDATA%\\Android\\Sdk'],
      },
      {
        order: 5,
        title: 'Set environment variables',
        description: 'Add ANDROID_HOME and JAVA_HOME to System Environment Variables.',
        tips: [
          'ANDROID_HOME = %LOCALAPPDATA%\\Android\\Sdk',
          'JAVA_HOME = C:\\Program Files\\Microsoft\\jdk-17.x.x',
          'Add to PATH: %ANDROID_HOME%\\platform-tools',
          'Use System Properties → Environment Variables GUI',
        ],
      },
      {
        order: 6,
        title: 'Enable HAXM or Hyper-V',
        description: 'Hardware acceleration is required for acceptable emulator performance.',
        tips: [
          'Intel CPUs: install HAXM via SDK Manager',
          'AMD CPUs: enable Hyper-V in Windows Features',
          'Check BIOS: virtualization (VT-x / AMD-V) must be enabled',
        ],
      },
      {
        order: 7,
        title: 'Verify setup',
        description: 'Create and run a test project.',
        commands: ['npx @react-native-community/cli@latest init TestApp', 'cd TestApp && npx react-native run-android'],
      },
    ],
  },
  {
    id: 'linux-android-setup',
    name: 'Linux — Android Development Setup',
    description: 'Complete setup guide for React Native Android development on Linux (Ubuntu/Debian).',
    keywords: ['linux', 'ubuntu', 'debian', 'android', 'setup linux', 'kvm'],
    os: 'linux',
    targetPlatform: 'android',
    prerequisites: ['Ubuntu 20.04+ or Debian 11+', '16GB+ RAM', 'KVM support for emulator acceleration'],
    steps: [
      {
        order: 1,
        title: 'Install Node.js via nvm',
        description: 'Install Node Version Manager and Node.js 20.',
        commands: [
          'curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.7/install.sh | bash',
          'nvm install 20',
        ],
      },
      {
        order: 2,
        title: 'Install JDK 17',
        description: 'Install OpenJDK 17 from package manager.',
        commands: ['sudo apt install -y openjdk-17-jdk'],
        tips: ['Verify: java -version should show 17.x', 'Set JAVA_HOME: export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64'],
      },
      {
        order: 3,
        title: 'Install Android Studio',
        description: 'Download from developer.android.com or use snap.',
        commands: ['sudo snap install android-studio --classic'],
      },
      {
        order: 4,
        title: 'Install Watchman',
        description: 'Build from source on Linux.',
        commands: [
          'sudo apt install -y autoconf automake build-essential libtool pkg-config',
          'git clone https://github.com/facebook/watchman.git && cd watchman && git checkout v2024.01.01.00 && ./autogen.sh && ./configure && make && sudo make install',
        ],
        tips: ['Alternatively, Metro works without Watchman but is slower for large projects'],
      },
      {
        order: 5,
        title: 'Configure KVM for emulator',
        description: 'Enable KVM hardware acceleration for the Android emulator.',
        commands: ['sudo apt install -y qemu-kvm', 'sudo adduser $USER kvm'],
        tips: ['Reboot after adding user to kvm group', 'Check: kvm-ok should show "KVM acceleration can be used"'],
      },
      {
        order: 6,
        title: 'Set environment variables',
        description: 'Add to ~/.bashrc or ~/.zshrc.',
        commands: [
          'echo \'export ANDROID_HOME=$HOME/Android/Sdk\' >> ~/.bashrc',
          'echo \'export PATH=$PATH:$ANDROID_HOME/emulator:$ANDROID_HOME/platform-tools\' >> ~/.bashrc',
          'source ~/.bashrc',
        ],
      },
    ],
  },
  {
    id: 'expo-quickstart',
    name: 'Expo Quick Start (Any OS)',
    description: 'Fastest way to start React Native development using Expo — works on macOS, Windows, and Linux.',
    keywords: ['expo', 'quick start', 'beginner', 'fast', 'easy', 'any os', 'cross platform setup'],
    os: 'common',
    targetPlatform: 'both',
    prerequisites: ['Node.js 18+', 'A physical iOS/Android device OR emulator/simulator'],
    steps: [
      {
        order: 1,
        title: 'Install Node.js',
        description: 'Download from nodejs.org or use a version manager (nvm, fnm).',
        commands: ['node --version'],
      },
      {
        order: 2,
        title: 'Create Expo project',
        description: 'Use create-expo-app for instant project scaffolding.',
        commands: ['npx create-expo-app@latest my-app', 'cd my-app'],
      },
      {
        order: 3,
        title: 'Start development server',
        description: 'Run Metro bundler and display QR code for Expo Go.',
        commands: ['npx expo start'],
      },
      {
        order: 4,
        title: 'Run on device',
        description: 'Install Expo Go app on your phone and scan the QR code.',
        tips: [
          'iOS: scan QR code with Camera app',
          'Android: scan QR code from Expo Go app',
          'Same WiFi network required for development',
        ],
      },
      {
        order: 5,
        title: 'Run on simulator/emulator (optional)',
        description: 'Press i for iOS Simulator (macOS only) or a for Android Emulator.',
        tips: [
          'iOS Simulator requires Xcode (macOS only)',
          'Android Emulator requires Android Studio on any OS',
        ],
      },
    ],
  },
];
