import type { NativeModuleGuide } from '../types.js';

export const RN_NATIVE_MODULE_GUIDES: NativeModuleGuide[] = [
  {
    id: 'turbo-module-overview',
    name: 'TurboModules Overview (New Architecture)',
    description: 'Understanding TurboModules — the new way to write native modules in React Native',
    keywords: ['turbo module', 'turbomodule', 'new architecture', 'native module', 'jsi'],
    platform: 'common',
    steps: [
      { order: 1, title: 'What are TurboModules?', description: 'TurboModules replace the old bridge-based native modules. They use JSI (JavaScript Interface) for direct, synchronous communication between JS and native code. Enabled by default in RN 0.76+.', tips: ['TurboModules are type-safe via codegen from a spec file', 'They load lazily (only when first used)', 'Synchronous calls are possible (no bridge serialization)'] },
      { order: 2, title: 'Create a TypeScript spec', description: 'Define the native module interface in a spec file.', codeExample: `// src/NativeMyModule.ts
import type { TurboModule } from 'react-native';
import { TurboModuleRegistry } from 'react-native';

export interface Spec extends TurboModule {
  multiply(a: number, b: number): number;       // sync
  getDeviceName(): Promise<string>;              // async
  addListener(eventName: string): void;
  removeListeners(count: number): void;
}

export default TurboModuleRegistry.getEnforcing<Spec>('MyModule');` },
      { order: 3, title: 'Run codegen', description: 'Codegen generates native interfaces from the spec.', codeExample: `// package.json
{
  "codegenConfig": {
    "name": "MyModuleSpec",
    "type": "modules",
    "jsSrcsDir": "src",
    "android": { "javaPackageName": "com.myapp.mymodule" }
  }
}

// Run: cd android && ./gradlew generateCodegenArtifactsFromSchema
// Or: cd ios && pod install (triggers codegen automatically)` },
      { order: 4, title: 'Implement native code', description: 'Implement the generated interface in Swift/Kotlin.', tips: ['iOS: Implement the ObjC++ protocol generated by codegen', 'Android: Extend the generated abstract class', 'See platform-specific guides below'] },
    ],
  },
  {
    id: 'turbo-module-ios',
    name: 'TurboModule: iOS Implementation (Swift)',
    description: 'Step-by-step guide to implementing a TurboModule in Swift for iOS',
    keywords: ['turbo module ios', 'swift native module', 'ios native', 'objc', 'swift'],
    platform: 'ios',
    steps: [
      { order: 1, title: 'Create Swift implementation', description: 'Create a Swift class that implements the codegen protocol.', codeExample: `// ios/MyModule.swift
import Foundation

@objc(MyModule)
class MyModule: NSObject {
  @objc func multiply(_ a: Double, b: Double) -> NSNumber {
    return NSNumber(value: a * b)
  }

  @objc func getDeviceName(_ resolve: @escaping RCTPromiseResolveBlock,
                            reject: @escaping RCTPromiseRejectBlock) {
    resolve(UIDevice.current.name)
  }

  @objc static func requiresMainQueueSetup() -> Bool { return false }
}` },
      { order: 2, title: 'Create ObjC bridging header', description: 'Register the module with React Native.', codeExample: `// ios/MyModule.mm
#import <React/RCTBridgeModule.h>

@interface RCT_EXTERN_MODULE(MyModule, NSObject)
RCT_EXTERN_METHOD(multiply:(double)a b:(double)b)
RCT_EXTERN_METHOD(getDeviceName:(RCTPromiseResolveBlock)resolve
                  reject:(RCTPromiseRejectBlock)reject)
@end` },
      { order: 3, title: 'Run pod install', description: 'Install and build.', tips: ['cd ios && pod install', 'Build in Xcode to verify compilation'] },
    ],
  },
  {
    id: 'turbo-module-android',
    name: 'TurboModule: Android Implementation (Kotlin)',
    description: 'Step-by-step guide to implementing a TurboModule in Kotlin for Android',
    keywords: ['turbo module android', 'kotlin native module', 'android native', 'java native'],
    platform: 'android',
    steps: [
      { order: 1, title: 'Create Kotlin implementation', description: 'Create a Kotlin class extending ReactContextBaseJavaModule.', codeExample: `// android/app/src/main/java/com/myapp/MyModule.kt
package com.myapp

import com.facebook.react.bridge.*

class MyModule(context: ReactApplicationContext) : ReactContextBaseJavaModule(context) {
  override fun getName() = "MyModule"

  @ReactMethod(isBlockingSynchronousMethod = true)
  fun multiply(a: Double, b: Double): Double = a * b

  @ReactMethod
  fun getDeviceName(promise: Promise) {
    promise.resolve(android.os.Build.MODEL)
  }
}` },
      { order: 2, title: 'Create package and register', description: 'Create a ReactPackage and register in MainApplication.', codeExample: `// MyModulePackage.kt
package com.myapp

import com.facebook.react.ReactPackage
import com.facebook.react.bridge.NativeModule
import com.facebook.react.bridge.ReactApplicationContext
import com.facebook.react.uimanager.ViewManager

class MyModulePackage : ReactPackage {
  override fun createNativeModules(context: ReactApplicationContext): List<NativeModule> =
    listOf(MyModule(context))
  override fun createViewManagers(context: ReactApplicationContext): List<ViewManager<*, *>> =
    emptyList()
}

// MainApplication.kt: add MyModulePackage() to getPackages()` },
      { order: 3, title: 'Build and test', description: 'Rebuild the Android project.', tips: ['cd android && ./gradlew clean assembleDebug', 'Check adb logcat for registration errors'] },
    ],
  },
  {
    id: 'fabric-component',
    name: 'Fabric Native Component (New Architecture)',
    description: 'Create custom native UI components using the Fabric renderer',
    keywords: ['fabric', 'native component', 'custom view', 'ui component', 'new architecture ui'],
    platform: 'common',
    steps: [
      { order: 1, title: 'What is Fabric?', description: 'Fabric is the new rendering system that replaces the old UIManager bridge. It enables synchronous layout, concurrent rendering, and direct native component access.', tips: ['Fabric components use codegen like TurboModules', 'Define a component spec → codegen → implement native view'] },
      { order: 2, title: 'Create component spec', description: 'Define the component props in a spec file.', codeExample: `// src/NativeMyViewNativeComponent.ts
import type { ViewProps } from 'react-native';
import type { Float } from 'react-native/Libraries/Types/CodegenTypes';
import codegenNativeComponent from 'react-native/Libraries/Utilities/codegenNativeComponent';

interface NativeProps extends ViewProps {
  color?: string;
  radius?: Float;
}

export default codegenNativeComponent<NativeProps>('MyView');` },
      { order: 3, title: 'Implement native view', description: 'Implement the native view on each platform using the codegen output.', tips: ['iOS: Subclass RCTViewComponentView', 'Android: Extend SimpleViewManager or ViewGroupManager', 'Refer to React Native docs for detailed platform guides'] },
    ],
  },
  {
    id: 'bridge-to-new-arch',
    name: 'Migrating from Bridge to New Architecture',
    description: 'Guide for migrating existing native modules from the old bridge to TurboModules/Fabric',
    keywords: ['migration', 'bridge', 'new architecture migration', 'upgrade native module', 'interop'],
    platform: 'common',
    steps: [
      { order: 1, title: 'Check compatibility', description: 'Many libraries already support New Architecture. Check reactnative.directory.', tips: ['Filter by "New Architecture" on reactnative.directory', 'If a library is not updated, the interop layer may work automatically'] },
      { order: 2, title: 'Interop layer (automatic)', description: 'RN 0.74+ has an interop layer that allows old bridge modules to work with New Architecture without changes.', tips: ['Most old modules work via interop automatically', 'Performance is slightly lower than native TurboModules', 'Test thoroughly — some edge cases may break'] },
      { order: 3, title: 'Full migration steps', description: 'To fully migrate: 1) Create a TurboModule spec matching the old API. 2) Run codegen. 3) Implement native code using new interfaces. 4) Remove old bridge registration.', codeExample: `// Old bridge module:
// NativeModules.MyModule.doSomething()

// New TurboModule:
// 1. Create NativeMyModule.ts spec
// 2. Run codegen
// 3. Implement in Swift/Kotlin
// 4. Usage is the same: NativeMyModule.doSomething()` },
      { order: 4, title: 'Enable New Architecture', description: 'Enable per-platform.', codeExample: `// Android: android/gradle.properties
newArchEnabled=true

// iOS: reinstall pods with flag
cd ios && RCT_NEW_ARCH_ENABLED=1 pod install` },
    ],
  },
];
