import type { ReleaseChecklistGuide } from '../types.js';

export const RN_RELEASE_CHECKLIST_GUIDES: ReleaseChecklistGuide[] = [
  {
    id: 'ios-release-checklist',
    name: 'iOS App Store Release Checklist',
    description: 'Complete checklist for submitting a React Native app to the Apple App Store.',
    keywords: ['ios', 'app store', 'apple', 'release', 'submit', 'checklist', 'review', 'testflight'],
    platform: 'ios',
    checklist: [
      { order: 1, item: 'Bundle identifier is correct', description: 'Verify CFBundleIdentifier in Info.plist matches App Store Connect.', critical: true },
      { order: 2, item: 'Version and build number updated', description: 'Increment CFBundleShortVersionString (marketing) and CFBundleVersion (build number).', critical: true },
      { order: 3, item: 'Code signing configured', description: 'Distribution certificate + provisioning profile for App Store (not Development or Ad Hoc).', critical: true },
      { order: 4, item: 'Hermes enabled', description: 'Hermes improves startup time and memory usage. Verify hermesEnabled: true.', critical: false },
      { order: 5, item: 'ProGuard/R8-equivalent optimizations', description: 'iOS uses bitcode (deprecated) and LLVM optimizations. Ensure Release scheme is optimized.', critical: false },
      { order: 6, item: 'App icons complete (all sizes)', description: '1024×1024 App Store icon + all device icon sizes in Assets.xcassets.', critical: true },
      { order: 7, item: 'Launch screen / splash configured', description: 'LaunchScreen.storyboard or expo-splash-screen with correct images.', critical: true },
      { order: 8, item: 'Privacy manifest (PrivacyInfo.xcprivacy)', description: 'Required since April 2024. Declare API usage reasons for required reason APIs.', critical: true },
      { order: 9, item: 'NSAppTransportSecurity (ATS)', description: 'Remove localhost exceptions. Ensure all network calls use HTTPS.', critical: true },
      { order: 10, item: 'Remove debug code', description: 'No console.log, no React DevTools, no Flipper in release builds.', critical: true },
      { order: 11, item: 'Screenshots prepared (all device sizes)', description: '6.7" (iPhone 15 Pro Max), 6.5", 5.5" + iPad if universal. Can use Fastlane Snapshot.', critical: true },
      { order: 12, item: 'App privacy details filled in', description: 'In App Store Connect, complete the App Privacy section (data collection practices).', critical: true },
      { order: 13, item: 'TestFlight testing', description: 'Upload build and test via TestFlight before submitting for review.', critical: true },
      { order: 14, item: 'Review Guidelines compliance', description: 'Read Apple\'s App Review Guidelines. Common rejections: login requirements, incomplete features, crashes.', critical: true },
    ],
    commonRejections: [
      { reason: 'Guideline 2.1 - App Completeness: Crashes or errors', fix: 'Test all flows thoroughly on real devices with release builds' },
      { reason: 'Guideline 2.3 - Accurate Metadata: Screenshots don\'t match app', fix: 'Use real app screenshots, not mockups' },
      { reason: 'Guideline 4.0 - Design: Login wall without guest mode', fix: 'Allow browsing content without login, or explain in review notes' },
      { reason: 'Guideline 5.1.1 - Data Collection: Missing privacy labels', fix: 'Complete App Privacy section in App Store Connect' },
      { reason: 'Guideline 2.5.1 - Software Requirements: Uses private APIs', fix: 'Remove any libraries using private iOS APIs' },
    ],
  },
  {
    id: 'android-release-checklist',
    name: 'Google Play Release Checklist',
    description: 'Complete checklist for submitting a React Native app to the Google Play Store.',
    keywords: ['android', 'google play', 'release', 'submit', 'checklist', 'review', 'aab', 'play store'],
    platform: 'android',
    checklist: [
      { order: 1, item: 'Application ID is correct', description: 'Verify applicationId in android/app/build.gradle matches Play Console.', critical: true },
      { order: 2, item: 'Version code and name updated', description: 'Increment versionCode (integer, must always increase) and versionName.', critical: true },
      { order: 3, item: 'Release signing configured', description: 'Upload keystore or use Play App Signing. NEVER lose your upload keystore.', critical: true },
      { order: 4, item: 'ProGuard/R8 enabled', description: 'minifyEnabled true and shrinkResources true in build.gradle for release.', critical: true },
      { order: 5, item: 'Hermes enabled', description: 'Hermes reduces APK size and improves startup time.', critical: false },
      { order: 6, item: 'Build AAB (not APK)', description: 'Google Play requires Android App Bundle format: ./gradlew bundleRelease.', critical: true },
      { order: 7, item: 'Target SDK version >= 34', description: 'Google Play requires targetSdkVersion 34+ for new apps and updates.', critical: true },
      { order: 8, item: '64-bit support included', description: 'Ensure arm64-v8a is included in APK/AAB. Remove abiFilters if restrictive.', critical: true },
      { order: 9, item: 'App icons and adaptive icon', description: 'Adaptive icon (foreground + background layers) + legacy icon for older devices.', critical: true },
      { order: 10, item: 'Remove debug config', description: 'Remove android:debuggable, cleartext traffic permission, and development settings.', critical: true },
      { order: 11, item: 'Screenshots prepared', description: 'Phone + tablet (if supported) + feature graphic (1024×500).', critical: true },
      { order: 12, item: 'Content rating questionnaire', description: 'Complete the IARC content rating questionnaire in Play Console.', critical: true },
      { order: 13, item: 'Data safety section', description: 'Complete the Data safety form in Play Console (required since July 2022).', critical: true },
      { order: 14, item: 'Testing track rollout', description: 'Upload to internal/closed/open testing before production release.', critical: true },
    ],
    commonRejections: [
      { reason: 'Policy violation: Deceptive behavior', fix: 'Ensure app description accurately reflects functionality' },
      { reason: 'Crashes on specific devices', fix: 'Test on multiple device types using Firebase Test Lab' },
      { reason: 'Missing privacy policy', fix: 'Add privacy policy URL in Play Console and in-app settings' },
      { reason: 'Target SDK too low', fix: 'Update targetSdkVersion to 34+ and test behavioral changes' },
      { reason: 'Permissions not justified', fix: 'Remove unused permissions from AndroidManifest.xml' },
    ],
  },
  {
    id: 'common-release-checklist',
    name: 'Cross-Platform Pre-Release Checklist',
    description: 'Universal quality checks before releasing any React Native app.',
    keywords: ['pre-release', 'quality', 'qa', 'testing', 'checklist', 'both platforms', 'general release'],
    platform: 'common',
    checklist: [
      { order: 1, item: 'All tests passing', description: 'Run full test suite: unit tests, integration tests, E2E tests.', critical: true },
      { order: 2, item: 'TypeScript strict mode clean', description: 'No TypeScript errors with strict mode enabled.', critical: true },
      { order: 3, item: 'Lint clean', description: 'ESLint and Prettier checks pass with no warnings.', critical: false },
      { order: 4, item: 'Performance profiling', description: 'Test on low-end devices. Check startup time, scroll performance, memory usage.', critical: true },
      { order: 5, item: 'Offline behavior tested', description: 'App handles network loss gracefully with user-friendly messages.', critical: true },
      { order: 6, item: 'Deep links tested', description: 'Verify all deep link routes work on both platforms.', critical: false },
      { order: 7, item: 'Accessibility check', description: 'VoiceOver (iOS) and TalkBack (Android) navigate correctly. Touch targets >= 44pt.', critical: true },
      { order: 8, item: 'Analytics and crash reporting', description: 'Verify Sentry/Crashlytics/analytics SDK is configured and reporting to production.', critical: true },
      { order: 9, item: 'Environment variables are production values', description: 'API URLs, keys, and feature flags point to production. No staging/dev values.', critical: true },
      { order: 10, item: 'Sensitive data not in bundle', description: 'No API secrets, private keys, or passwords hardcoded in JavaScript bundle.', critical: true },
      { order: 11, item: 'OTA update strategy decided', description: 'If using EAS Update/CodePush, verify channel/deployment configuration.', critical: false },
      { order: 12, item: 'Rollback plan ready', description: 'Know how to revert: previous app store version, OTA rollback, or feature flags.', critical: true },
    ],
  },
];
