import type { TroubleshootRecipe } from '../types.js';

export const RN_TROUBLESHOOT_RECIPES: TroubleshootRecipe[] = [
  {
    id: 'white-screen-launch',
    symptom: 'White screen on app launch',
    description: 'App shows a blank white screen and never loads the JS bundle.',
    platform: 'common',
    keywords: ['white screen', 'blank screen', 'not loading', 'launch', 'splash'],
    checks: [
      { order: 1, action: 'Check Metro is running', expected: 'Metro terminal shows "Ready"', ifFail: 'Start Metro: npx react-native start --reset-cache' },
      { order: 2, action: 'Check device is connected', expected: 'adb devices (Android) or simulator is running (iOS)', ifFail: 'Connect device or start simulator' },
      { order: 3, action: 'Check bundle URL', expected: 'Device can reach Metro server (localhost:8081)', ifFail: 'Android: adb reverse tcp:8081 tcp:8081. iOS: check same Wi-Fi network' },
      { order: 4, action: 'Check for JS errors', expected: 'No red screen or LogBox errors', ifFail: 'Fix the JS error shown. Check console for details' },
      { order: 5, action: 'Check release build bundle', expected: 'Release builds bundle JS into the app', ifFail: 'Rebuild: npx react-native bundle --entry-file index.js --platform [ios|android] --dev false --bundle-output ...' },
    ],
    commonCause: 'Metro bundler not running, device cannot reach Metro server, or JS error preventing render.',
    fix: ['npx react-native start --reset-cache', 'adb reverse tcp:8081 tcp:8081 (Android)', 'Check console for JS errors'],
  },
  {
    id: 'crash-on-launch-release',
    symptom: 'App crashes on launch in release mode (but works in debug)',
    description: 'Debug build works fine, but the release/production build crashes immediately.',
    platform: 'common',
    keywords: ['crash', 'release', 'production crash', 'works in debug', 'launch crash'],
    checks: [
      { order: 1, action: 'Check ProGuard rules (Android)', expected: 'proguard-rules.pro includes keep rules for RN and libraries', ifFail: 'Add missing keep rules. Check library docs for required ProGuard rules' },
      { order: 2, action: 'Check Hermes bytecode compilation', expected: 'Hermes should be enabled consistently', ifFail: 'Verify hermesEnabled=true in gradle.properties and Podfile' },
      { order: 3, action: 'Check native library linking', expected: 'All native libraries are linked for release', ifFail: 'Run: npx react-native link (legacy) or check auto-linking' },
      { order: 4, action: 'Check environment variables', expected: 'Release build has correct API URLs', ifFail: 'Verify .env.production or release build config' },
      { order: 5, action: 'Check crash logs', expected: 'Find the actual error', ifFail: 'iOS: Xcode → Window → Devices and Simulators → View Device Logs. Android: adb logcat *:E' },
    ],
    commonCause: 'ProGuard stripping needed classes, Hermes bytecode issues, or missing environment config.',
    fix: ['Check ProGuard rules for all native libraries', 'Verify Hermes is consistent between debug/release', 'Check adb logcat (Android) or Xcode device logs (iOS)'],
  },
  {
    id: 'pod-install-fail',
    symptom: 'pod install fails with errors',
    description: 'CocoaPods installation fails with various errors.',
    platform: 'ios',
    keywords: ['pod install', 'cocoapods', 'pods error', 'ios build fail', 'podfile'],
    checks: [
      { order: 1, action: 'Check Ruby version', expected: 'ruby >= 2.7', ifFail: 'Install rbenv: brew install rbenv && rbenv install 3.2.0' },
      { order: 2, action: 'Check CocoaPods version', expected: 'pod --version >= 1.13', ifFail: 'gem install cocoapods' },
      { order: 3, action: 'Try clean pod install', expected: 'Fresh installation succeeds', ifFail: 'cd ios && pod deintegrate && rm Podfile.lock && pod install' },
      { order: 4, action: 'Update pod repo', expected: 'Pod specs are up to date', ifFail: 'pod repo update && pod install' },
      { order: 5, action: 'Check Xcode CLI tools', expected: 'xcode-select -p shows valid path', ifFail: 'xcode-select --install' },
    ],
    commonCause: 'Outdated CocoaPods, stale pod cache, or Xcode CLI tools misconfiguration.',
    fix: ['cd ios && pod deintegrate && rm Podfile.lock && pod install', 'pod repo update', 'gem install cocoapods'],
  },
  {
    id: 'gradle-build-fail',
    symptom: 'Android Gradle build fails',
    description: 'Android build fails with Gradle-related errors.',
    platform: 'android',
    keywords: ['gradle', 'android build', 'build failed', 'gradle error', 'assembleDebug'],
    checks: [
      { order: 1, action: 'Check Java version', expected: 'java -version shows 17', ifFail: 'Install JDK 17 and set JAVA_HOME' },
      { order: 2, action: 'Check ANDROID_HOME', expected: 'echo $ANDROID_HOME shows valid SDK path', ifFail: 'Set ANDROID_HOME in ~/.bashrc or ~/.zshrc' },
      { order: 3, action: 'Try clean build', expected: 'Clean build succeeds', ifFail: 'cd android && ./gradlew clean && ./gradlew assembleDebug' },
      { order: 4, action: 'Check Gradle heap memory', expected: 'gradle.properties has org.gradle.jvmargs=-Xmx4g', ifFail: 'Add org.gradle.jvmargs=-Xmx4096m to android/gradle.properties' },
      { order: 5, action: 'Check dependency conflicts', expected: 'No duplicate class errors', ifFail: 'Run: cd android && ./gradlew dependencies to inspect tree' },
    ],
    commonCause: 'Wrong Java version, insufficient heap memory, or dependency version conflicts.',
    fix: ['Verify Java 17 with java -version', 'cd android && ./gradlew clean', 'Increase Gradle heap in gradle.properties'],
  },
  {
    id: 'metro-slow',
    symptom: 'Metro bundler is extremely slow',
    description: 'Metro takes a long time to start or reload changes.',
    platform: 'common',
    keywords: ['metro slow', 'slow bundler', 'slow reload', 'hot reload slow', 'bundling slow'],
    checks: [
      { order: 1, action: 'Clear Metro cache', expected: 'Fresh cache speeds up bundling', ifFail: 'npx react-native start --reset-cache' },
      { order: 2, action: 'Check watchman', expected: 'watchman is installed and running', ifFail: 'brew install watchman && watchman watch-del-all' },
      { order: 3, action: 'Check node_modules size', expected: 'Reasonable number of dependencies', ifFail: 'Audit deps: npx depcheck. Remove unused packages' },
      { order: 4, action: 'Check for circular imports', expected: 'No circular dependency chains', ifFail: 'Use npx madge --circular to find circular imports' },
    ],
    commonCause: 'Stale Metro cache, missing watchman, or too many/circular dependencies.',
    fix: ['npx react-native start --reset-cache', 'brew install watchman', 'watchman watch-del-all'],
  },
  {
    id: 'app-too-large',
    symptom: 'App binary size is too large',
    description: 'APK/AAB or IPA file is larger than expected.',
    platform: 'common',
    keywords: ['app size', 'bundle size', 'large app', 'apk size', 'ipa size', 'binary size'],
    checks: [
      { order: 1, action: 'Enable Hermes', expected: 'Hermes bytecode is smaller than JSC', ifFail: 'Enable hermesEnabled=true in gradle.properties' },
      { order: 2, action: 'Enable ProGuard (Android)', expected: 'minifyEnabled=true, shrinkResources=true in release build', ifFail: 'Set in android/app/build.gradle buildTypes.release' },
      { order: 3, action: 'Use AAB format (Android)', expected: 'AAB enables dynamic delivery (15-20% smaller)', ifFail: 'Build with ./gradlew bundleRelease instead of assembleRelease' },
      { order: 4, action: 'Check image assets', expected: 'Images are optimized (WebP, compressed PNG)', ifFail: 'Convert to WebP, remove unused assets' },
      { order: 5, action: 'Analyze bundle', expected: 'No unexpectedly large dependencies', ifFail: 'Use react-native-bundle-visualizer or source-map-explorer' },
    ],
    commonCause: 'Unoptimized images, ProGuard disabled, or unnecessary large dependencies.',
    fix: ['Enable Hermes + ProGuard', 'Use AAB for Android', 'Optimize images to WebP', 'npx react-native-bundle-visualizer'],
  },
  {
    id: 'keyboard-covers-input',
    symptom: 'Keyboard covers text input fields',
    description: 'When a text input is focused, the keyboard covers it and the user cannot see what they type.',
    platform: 'common',
    keywords: ['keyboard', 'text input', 'keyboard covers', 'keyboard avoiding', 'input hidden'],
    checks: [
      { order: 1, action: 'Use KeyboardAvoidingView', expected: 'Content shifts up when keyboard appears', ifFail: 'Wrap form in KeyboardAvoidingView with behavior prop' },
      { order: 2, action: 'Check behavior prop', expected: 'iOS: "padding", Android: "height" or undefined', ifFail: 'behavior={Platform.OS === "ios" ? "padding" : undefined}' },
      { order: 3, action: 'Check ScrollView', expected: 'Content is scrollable when keyboard is open', ifFail: 'Wrap in ScrollView with keyboardShouldPersistTaps="handled"' },
    ],
    commonCause: 'Missing KeyboardAvoidingView or wrong behavior prop for the platform.',
    fix: ['Wrap form in <KeyboardAvoidingView behavior={Platform.OS === "ios" ? "padding" : undefined}>', 'Use ScrollView with keyboardShouldPersistTaps="handled"', 'Consider react-native-keyboard-aware-scroll-view for complex forms'],
  },
  {
    id: 'images-not-loading',
    symptom: 'Remote images not loading (showing blank or broken)',
    description: 'Images from URLs do not display in the app.',
    platform: 'common',
    keywords: ['image not loading', 'broken image', 'remote image', 'image blank', 'http image'],
    checks: [
      { order: 1, action: 'Check Image source format', expected: 'source={{ uri: "https://..." }} with width/height', ifFail: 'Remote images MUST have explicit width and height style' },
      { order: 2, action: 'Check HTTPS', expected: 'URL uses HTTPS', ifFail: 'iOS blocks HTTP by default. Use HTTPS or add NSAppTransportSecurity exception' },
      { order: 3, action: 'Check network', expected: 'Device can reach the URL', ifFail: 'Test URL in device browser. Check CORS is not an issue' },
      { order: 4, action: 'Check cache', expected: 'Image is not blocked by cache', ifFail: 'Add cache: "reload" to Image source or use FastImage library' },
    ],
    commonCause: 'Missing width/height for remote images, HTTP URL blocked by iOS ATS, or CORS issues.',
    fix: ['Add explicit width and height to Image style', 'Use HTTPS URLs', 'Consider react-native-fast-image for better caching'],
  },
  {
    id: 'navigation-back-android',
    symptom: 'Android hardware back button does not work correctly',
    description: 'Pressing the Android back button exits the app instead of going back, or does nothing.',
    platform: 'android',
    keywords: ['back button', 'android back', 'hardware back', 'navigation back', 'back handler'],
    checks: [
      { order: 1, action: 'Check React Navigation setup', expected: 'NavigationContainer wraps the app', ifFail: 'Ensure NavigationContainer is at the root of your app' },
      { order: 2, action: 'Check nested navigators', expected: 'Back behavior respects navigator hierarchy', ifFail: 'Use navigation.goBack() or custom BackHandler logic' },
      { order: 3, action: 'Check BackHandler for custom behavior', expected: 'Custom back handler is registered correctly', ifFail: 'Use BackHandler.addEventListener and return true to prevent default' },
    ],
    commonCause: 'React Navigation handles back button automatically. Custom screens or modals may need BackHandler.',
    fix: ['Verify NavigationContainer wraps the app', 'Use BackHandler.addEventListener for custom back behavior', 'For modals: handle back to dismiss modal first'],
  },
  {
    id: 'fonts-not-loading',
    symptom: 'Custom fonts not rendering (showing system font instead)',
    description: 'Custom fonts are configured but the app shows the default system font.',
    platform: 'common',
    keywords: ['font', 'custom font', 'font not loading', 'typography', 'font family'],
    checks: [
      { order: 1, action: 'Check font file format', expected: '.ttf or .otf files in assets directory', ifFail: 'Place fonts in assets/fonts/ directory' },
      { order: 2, action: 'Link fonts', expected: 'Fonts are linked to native projects', ifFail: 'Expo: use expo-font + useFonts hook. Bare RN: npx react-native-asset' },
      { order: 3, action: 'Check fontFamily name', expected: 'fontFamily matches the actual font name (not file name)', ifFail: 'iOS: use the PostScript name. Android: use the file name without extension' },
      { order: 4, action: 'Rebuild', expected: 'Fonts appear after native rebuild', ifFail: 'Clean build: rm -rf ios/build android/app/build && rebuild' },
    ],
    commonCause: 'Font family name mismatch (iOS uses PostScript name, Android uses file name), or fonts not linked.',
    fix: ['Verify font names: iOS uses PostScript name, Android uses filename', 'Expo: npx expo install expo-font && use useFonts()', 'Bare RN: npx react-native-asset && rebuild'],
  },
];
