import type { VersionUpgradeGuide } from '../types.js';

export const RN_UPGRADE_GUIDES: VersionUpgradeGuide[] = [
  {
    id: 'rn-072-to-073',
    from: '0.72',
    to: '0.73',
    name: 'React Native 0.72 → 0.73',
    description: 'Major: Java 17 required, Flipper removed, debugger changes',
    keywords: ['0.72', '0.73', 'java 17', 'flipper', 'debugger'],
    majorChanges: [
      'Java 17 required (was Java 11)',
      'Flipper removed from default template',
      'New React Native Debugger replaces Hermes debugger',
      'Kotlin updated to 1.8.10',
      'Minimum iOS deployment target 13.4',
    ],
    steps: [
      { order: 1, title: 'Update Java to 17', description: 'Install JDK 17 and update JAVA_HOME.', commands: ['brew install openjdk@17', 'export JAVA_HOME=$(/usr/libexec/java_home -v 17)'], breakingChange: true, tips: ['Verify: java -version should show 17'] },
      { order: 2, title: 'Run RN Upgrade Helper', description: 'Use the upgrade helper to see all file diffs.', commands: ['# Visit https://react-native-community.github.io/upgrade-helper/?from=0.72.0&to=0.73.0', 'npx @react-native-community/cli upgrade 0.73'], breakingChange: false },
      { order: 3, title: 'Remove Flipper', description: 'Flipper is removed from the default template. Remove Flipper dependencies if present.', commands: ['# iOS: Remove Flipper pods from Podfile', '# Android: Remove flipper dependencies from build.gradle'], breakingChange: true, tips: ['Use Reactotron or built-in DevTools instead'] },
      { order: 4, title: 'Update Gradle and AGP', description: 'Update Gradle wrapper to 8.0+ and AGP to match.', commands: ['cd android && ./gradlew wrapper --gradle-version 8.3'], breakingChange: true },
      { order: 5, title: 'Reinstall dependencies', description: 'Clean install all dependencies.', commands: ['rm -rf node_modules && npm install', 'cd ios && pod deintegrate && pod install'], breakingChange: false },
      { order: 6, title: 'Test debugger', description: 'The new debugger uses "j" in Metro terminal instead of Chrome DevTools.', commands: ['npx react-native start', '# Press "j" to open new debugger'], breakingChange: false },
    ],
  },
  {
    id: 'rn-073-to-074',
    from: '0.73',
    to: '0.74',
    name: 'React Native 0.73 → 0.74',
    description: 'Major: Android namespace required, Yoga 3.0, Bridgeless mode',
    keywords: ['0.73', '0.74', 'namespace', 'yoga', 'bridgeless'],
    majorChanges: [
      'Android namespace required in build.gradle (AGP 8.0+ mandate)',
      'Yoga 3.0 (layout engine update — may change some layouts)',
      'Bridgeless mode available (opt-in)',
      'Removed deprecated APIs',
    ],
    steps: [
      { order: 1, title: 'Add Android namespace', description: 'Add namespace to android/app/build.gradle. Required by AGP 8.0+.', commands: ['# android/app/build.gradle:', '# android { namespace "com.yourapp" }'], breakingChange: true, tips: ['Must match applicationId', 'Remove package from AndroidManifest.xml <manifest> tag'] },
      { order: 2, title: 'Run upgrade helper', description: 'Apply all template changes.', commands: ['npx @react-native-community/cli upgrade 0.74'], breakingChange: false },
      { order: 3, title: 'Test layout changes', description: 'Yoga 3.0 may change some edge-case layouts. Test all screens.', commands: [], breakingChange: true, tips: ['Row-reverse + gap behavior changed', 'Check flexbox edge cases'] },
      { order: 4, title: 'Clean rebuild', description: 'Full clean rebuild after upgrade.', commands: ['rm -rf node_modules && npm install', 'cd ios && pod deintegrate && pod install', 'cd android && ./gradlew clean'], breakingChange: false },
    ],
  },
  {
    id: 'rn-074-to-075',
    from: '0.74',
    to: '0.75',
    name: 'React Native 0.74 → 0.75',
    description: 'New Architecture preparation, min iOS 15.1, Android API 24+',
    keywords: ['0.74', '0.75', 'new architecture', 'ios 15', 'api 24'],
    majorChanges: [
      'Minimum iOS deployment target raised to 15.1',
      'Minimum Android API raised to 24',
      'New Architecture is now the recommended direction',
      'Auto-linking improvements',
      'Expo SDK 51 compatibility',
    ],
    steps: [
      { order: 1, title: 'Update iOS deployment target', description: 'Set minimum iOS deployment target to 15.1.', commands: ['# Podfile: platform :ios, \'15.1\'', '# Xcode: Target → General → Minimum Deployments → iOS 15.1'], breakingChange: true, tips: ['This drops support for iOS 13-14 devices'] },
      { order: 2, title: 'Update Android minSdk', description: 'Raise minSdkVersion to 24.', commands: ['# android/app/build.gradle: minSdkVersion = 24'], breakingChange: true, tips: ['Drops support for Android 6 (API 23)'] },
      { order: 3, title: 'Run upgrade helper', description: 'Apply all template changes.', commands: ['npx @react-native-community/cli upgrade 0.75'], breakingChange: false },
      { order: 4, title: 'Consider New Architecture', description: 'Enable New Architecture if your dependencies support it.', commands: ['# iOS: RCT_NEW_ARCH_ENABLED=1 pod install', '# Android: newArchEnabled=true in gradle.properties'], breakingChange: false, tips: ['Check each library for New Architecture support first'] },
      { order: 5, title: 'Clean rebuild', description: 'Full clean rebuild.', commands: ['rm -rf node_modules && npm install', 'cd ios && pod deintegrate && pod install'], breakingChange: false },
    ],
  },
  {
    id: 'rn-075-to-076',
    from: '0.75',
    to: '0.76',
    name: 'React Native 0.75 → 0.76',
    description: 'New Architecture default, React 18.3, new DevTools',
    keywords: ['0.75', '0.76', 'new architecture default', 'react 18', 'devtools'],
    majorChanges: [
      'New Architecture enabled by default',
      'React 18.3 (concurrent features)',
      'New React Native DevTools (replaces Flipper)',
      'Built-in network inspector',
      'Android edge-to-edge mode by default',
    ],
    steps: [
      { order: 1, title: 'Run upgrade helper', description: 'Apply all template file changes.', commands: ['npx @react-native-community/cli upgrade 0.76'], breakingChange: false },
      { order: 2, title: 'Test New Architecture compatibility', description: 'New Architecture is now default. Check all libraries.', commands: ['# Check: https://reactnative.directory/ (filter by New Architecture support)'], breakingChange: true, tips: ['If a library does not support New Architecture, disable it: newArchEnabled=false', 'Most popular libraries support it by now'] },
      { order: 3, title: 'Update React to 18.3', description: 'React 18 enables concurrent features. Check for issues with useEffect cleanup.', commands: ['npm install react@18.3 react-dom@18.3'], breakingChange: true, tips: ['StrictMode double-invokes effects in dev', 'Check for missing cleanup in useEffect'] },
      { order: 4, title: 'Handle Android edge-to-edge', description: 'Android apps now render behind status bar and navigation bar by default.', commands: [], breakingChange: true, tips: ['Use SafeAreaView or react-native-safe-area-context', 'Set android:windowLayoutInDisplayCutoutMode if needed'] },
      { order: 5, title: 'Clean rebuild', description: 'Full clean rebuild.', commands: ['rm -rf node_modules && npm install', 'cd ios && pod deintegrate && pod install', 'cd android && ./gradlew clean'], breakingChange: false },
    ],
  },
];
